// lib/api/signals.ts

import { z } from 'zod'; // Import zod
import { getCurrentUserToken } from './auth';
import { Timestamp } from 'firebase-admin/firestore'; // Import Timestamp

// Determine API base URL based on environment
const API_BASE = typeof window === 'undefined' 
  ? process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' // Server-side needs full URL
  : ''; // Client-side uses relative path starting with /api

// Signal types
export type SignalType = 'newsletter' | 'article';

// --- Zod Schema Definition ---
export const SignalSchema = z.object({
  id: z.string().optional(), // ID is usually generated by Firestore, but might be present
  type: z.enum(['newsletter', 'article']), // Use the defined SignalType values
  title: z.string().min(1, "Title is required"), // Ensure title is not empty
  description: z.string().min(1, "Description is required"), // Ensure description is not empty
  url: z.string().url("Must be a valid URL"), // Validate URL format
  source: z.string().nullable().optional(), // Allow string, null, or undefined (will be sanitized to null)
  author: z.string().nullable().optional(),
  dateAdded: z.string().datetime({ message: "Invalid date format" }).optional(), // Validate ISO 8601 date string
  featured: z.boolean().optional().default(false),
  tags: z.array(z.string()).optional().default([]),
  imageUrl: z.string().url({ message: "Invalid image URL" }).nullable().optional(), // Allow valid URL, null, or undefined
  // Specific fields for subtypes (optional)
  issueNumber: z.string().optional(),
  frequency: z.string().optional(),
  publicationName: z.string().optional(),
  readingTime: z.number().int().positive().optional(),
  // Social share not included in schema as it's likely handled separately
});

export type SignalSchemaType = z.infer<typeof SignalSchema>;

// Helper to convert Firestore Timestamps back to ISO strings for API response
export function convertFirestoreSignalToApiResponse(docData: FirebaseFirestore.DocumentData | undefined | null): Record<string, any> {
  if (!docData) return {};
  const data: Record<string, any> = { ...docData };
  for (const key in data) {
    if (data[key] instanceof Timestamp) { 
      data[key] = data[key].toDate().toISOString();
    } else if (data[key] === undefined) {
       // Convert undefined (shouldn't happen often) to null for consistency
       data[key] = null;
    }
  }
  return data; 
}

// Helper to sanitize incoming API data (convert undefined to null)
export function sanitizeData(body: any): Record<string, any> {
  if (!body || typeof body !== 'object') return {};
  return Object.entries(body).reduce((acc, [key, value]) => {
      // Keep null values as null, convert undefined to null
      acc[key] = value === undefined ? null : value;
      return acc;
  }, {} as Record<string, any>);
}

// Signal interface
export interface Signal {
  id?: string;
  type: SignalType;
  title: string;
  description: string;
  url: string;
  source: string;
  author?: string;
  dateAdded?: string;
  featured?: boolean;
  tags?: string[];
  imageUrl?: string;
  socialShare?: {
    linkedin?: boolean;
    twitter?: boolean;
    bluesky?: boolean;
  };
}

// Newsletter interface
export interface Newsletter extends Signal {
  type: 'newsletter';
  issueNumber?: string;
  frequency?: string;
}

// Article interface
export interface Article extends Signal {
  type: 'article';
  publicationName?: string;
  readingTime?: number;
}

// Get all signals
export async function getAllSignals(): Promise<Signal[]> {
  try {
    // Try server API first
    const token = await getCurrentUserToken();
    
    if (token) {
      try {
        const response = await fetch(`${API_BASE}/api/signals`, {
          headers: {
            Authorization: `Bearer ${token}`
          }
        });
        
        if (response.ok) {
          const data = await response.json();
          return data.success ? data.data : [];
        }
      } catch (error) {
        console.error('Server API error:', error);
        // Continue with fallback
      }
    }
    
    // No client-side fallback. All signal fetching must go through the server API.
    return [];

  } catch (error) {
    console.error('Error getting signals:', error);
    return [];
  }
}

// Get signals by type
export async function getSignalsByType(type: SignalType): Promise<Signal[]> {
  try {
    // Try server API first
    const token = await getCurrentUserToken();
    if (token) {
      try {
        const response = await fetch(`${API_BASE}/api/signals?type=${type}`, {
          headers: {
            Authorization: `Bearer ${token}`
          }
        });
        
        if (response.ok) {
          const data = await response.json();
          return data.success ? data.data : [];
        }
      } catch (error) {
        console.error('Server API error:', error);
        // Continue with fallback
      }
    }
    
    // No client-side fallback. All signal fetching must go through the server API.
    return [];

  } catch (error) {
    console.error(`Error getting signals by type ${type}:`, error);
    return [];
  }
}

// Add a new signal
export async function addSignal(signal: Signal): Promise<Signal | null> {
  try {
    // Try server API first
    const token = await getCurrentUserToken();
    if (token) {
      try {
        const response = await fetch(`${API_BASE}/api/signals`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`
          },
          body: JSON.stringify(signal)
        });
        
        if (response.ok) {
          const data = await response.json();
          return data.success ? data.data : null;
        }
      } catch (error) {
        console.error('Server API error:', error);
        // Continue with fallback
      }
    }
    
    // No client-side fallback. All signal creation must go through the server API.
    return null;

  } catch (error) {
    console.error('Error adding signal:', error);
    return null;
  }
}

// Update a signal
export async function updateSignal(signal: Signal): Promise<boolean> {
  if (!signal.id) return false;
  
  try {
    // Try server API first
    const token = await getCurrentUserToken();
    if (token) {
      try {
        const response = await fetch(`${API_BASE}/api/signals`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`
          },
          body: JSON.stringify(signal)
        });
        
        if (response.ok) {
          return true;
        }
      } catch (error) {
        console.error('Server API error:', error);
        return false;
      }
    }
    
    return false;

  } catch (error) {
    console.error('Error updating signal:', error);
    return false;
  }
}

// Delete a signal
export async function deleteSignal(id: string): Promise<boolean> {
  try {
    // Try server API first
    const token = await getCurrentUserToken();
    if (token) {
      try {
        const response = await fetch(`${API_BASE}/api/signals?id=${id}`, {
          method: 'DELETE',
          headers: {
            Authorization: `Bearer ${token}`
          }
        });
        
        if (response.ok) {
          return true;
        }
      } catch (error) {
        console.error('Server API error:', error);
        // Continue with fallback
      }
    }
    
    // No client-side fallback. All signal deletions must go through the server API.
    return false;

  } catch (error) {
    console.error('Error deleting signal:', error);
    return false;
  }
}

/**
 * Get all newsletters
 */
export async function getAllNewsletters(options: {
  featured?: boolean;
  limit?: number;
} = {}): Promise<Newsletter[]> {
  const signals = await getAllSignals();
  let newsletters = signals.filter(s => s.type === 'newsletter') as Newsletter[];
  
  if (options.featured !== undefined) {
    newsletters = newsletters.filter(n => n.featured === options.featured);
  }
  
  if (options.limit && options.limit > 0) {
    newsletters = newsletters.slice(0, options.limit);
  }
  
  return newsletters;
}

/**
 * Get all articles
 */
export async function getAllArticles(options: {
  featured?: boolean;
  limit?: number;
} = {}): Promise<Article[]> {
  const signals = await getAllSignals();
  let articles = signals.filter(s => s.type === 'article') as Article[];
  
  if (options.featured !== undefined) {
    articles = articles.filter(a => a.featured === options.featured);
  }
  
  if (options.limit && options.limit > 0) {
    articles = articles.slice(0, options.limit);
  }
  
  return articles;
}