
// This file is generated at build time by generate-runtime-config.js
// Do not edit this file manually
window.runtimeConfig = {
  firebase: {
    apiKey: "AIzaSyD4a8iaxHP9xPGV5tR5LwvzDVa5Y9o5wGQ",
    authDomain: "personalsite-19189.firebaseapp.com",
    projectId: "personalsite-19189",
    storageBucket: "personalsite-19189.firebasestorage.app",
    messagingSenderId: "892517360036",
    appId: "1:892517360036:web:36dda234d9f3f79562e131",
    measurementId: ""
  },
  isProduction: false,
  basePath: "/personalsite"
};

// Also include alternate format for compatibility
window.__RUNTIME_CONFIG__ = {
  "firebase": {
    "apiKey": "AIzaSyD4a8iaxHP9xPGV5tR5LwvzDVa5Y9o5wGQ",
    "authDomain": "personalsite-19189.firebaseapp.com",
    "projectId": "personalsite-19189",
    "storageBucket": "personalsite-19189.firebasestorage.app",
    "messagingSenderId": "892517360036",
    "appId": "1:892517360036:web:36dda234d9f3f79562e131",
    "measurementId": ""
  },
  "isProduction": false,
  "basePath": "/personalsite"
};
