
// This file is generated at build time by generate-runtime-config.js
// Do not edit this file manually
window.runtimeConfig = {
  firebase: {
    // The actual Firebase config is set using environment variables during build and deploy
    // We only include the projectId in the public files for reference
    projectId: "personalsite-19189"
  },
  isProduction: true,
  basePath: "/personalsite"
};

// For development, automatically detect the correct base path
(function detectBasePath() {
  // Check if we're running on GitHub Pages (username.github.io/repo-name)
  const isGitHubPages = window.location.hostname.includes('github.io');
  
  if (isGitHubPages) {
    // Extract repo name from path for GitHub Pages
    const pathMatch = window.location.pathname.match(/^\/([^/]+)/);
    if (pathMatch) {
      window.runtimeConfig.basePath = pathMatch[0];
      console.log('Detected GitHub Pages path:', window.runtimeConfig.basePath);
    }
  } else if (window.location.hostname === 'localhost') {
    // If we're on localhost, keep the basePath that's already set
    console.log('Running on localhost with basePath:', window.runtimeConfig.basePath);
  }
})();
