// lib/schemas/signals.ts
import { z } from 'zod';

// Base Signal Schema using Zod
export const SignalSchema = z.object({
  id: z.string().optional(), // ID is optional as it's generated by Firestore
  type: z.enum(['newsletter', 'article'], { 
    required_error: 'Signal type must be either newsletter or article',
    invalid_type_error: 'Signal type must be either newsletter or article'
  }),
  title: z.string().min(1, { message: 'Title is required' }),
  description: z.string().min(1, { message: 'Description is required' }),
  url: z.string().url({ message: 'Must be a valid URL' }),
  source: z.string().nullable().optional(), // e.g., 'Twitter', 'RSS Feed', etc.
  author: z.string().nullable().optional(), 
  featured: z.boolean().default(false),
  tags: z.array(z.string()).min(1, { message: 'At least one tag is required' }),
  dateAdded: z.string().datetime({ message: 'Invalid date format. Use ISO 8601' }).optional(), // Optional on input, server sets if missing
  imageUrl: z.string().url({ message: 'Image URL must be a valid URL' }).nullable().optional(),
  // Newsletter specific fields
  publisher: z.string().nullable().optional(),
  frequency: z.string().nullable().optional(), 
  subscriptionUrl: z.string().url({ message: 'Subscription URL must be a valid URL' }).nullable().optional(),
  // Article specific fields
  publicationDate: z.string().datetime({ message: 'Invalid date format. Use ISO 8601' }).nullable().optional(),
  readingTime: z.number().int().positive().nullable().optional(),
  // Timestamps managed by Firestore, not typically part of input validation 
  // createdAt: z.string().datetime().optional(),
  // updatedAt: z.string().datetime().optional(),
}).refine(data => {
  if (data.type === 'newsletter' && !data.publisher) {
    return false; // Publisher is required for newsletters
  }
  return true;
}, { message: 'Publisher is required for newsletters', path: ['publisher'] });

export type SignalSchemaType = z.infer<typeof SignalSchema>;

// Signal interface (aligns with Zod schema, includes Firestore timestamps)
export interface Signal {
  id?: string;
  type: 'newsletter' | 'article';
  title: string;
  description: string;
  url: string;
  source?: string | null;
  author?: string | null;
  featured: boolean;
  tags: string[];
  dateAdded?: string | Date; // Can be string on input, Date object internally
  imageUrl?: string | null;
  createdAt?: string | Date; // Firestore timestamp
  updatedAt?: string | Date; // Firestore timestamp
}

// Newsletter interface extending Signal
export interface Newsletter extends Signal {
  type: 'newsletter';
  publisher: string; 
  frequency?: string | null;
  subscriptionUrl?: string | null;
}

// Article interface extending Signal
export interface Article extends Signal {
  type: 'article';
  publicationDate?: string | Date | null;
  readingTime?: number | null;
}

// Type guard for Newsletter
export function isNewsletter(signal: Signal): signal is Newsletter {
  return signal.type === 'newsletter';
}

// Type guard for Article
export function isArticle(signal: Signal): signal is Article {
  return signal.type === 'article';
}
